version: '3.4'

services:
  # take this as template and create own compose file as docker-compose.yml and run as usual - especially to change path to XBTUSD
  # useful comamnds docker-compose up --build (if code changes)
  #                 docker-compose up --force-recreate (if volumes etc changes)
  #                 docker-compose down (to stop the show)
  brute_force_search:
    build:
      context: ""
      dockerfile: ./brute_force/Dockerfile
    volumes:
      - /Users/mmark/Documents/credit_collections/credit_collections_rl:/credit_collections_rl #set your own path